trigger:
- master

stages:
- stage: amd64
  jobs:
  - template: debootstrap_architecture_template.yml
    parameters:
      arch: amd64
      qemu_arch: x86_64
- stage: arm64
  jobs:
  - template: debootstrap_architecture_template.yml
    pool: Ubuntu
    parameters:
      arch: arm64
      qemu_arch: aarch64
