trigger:
- master

steps:
  - template: debootstrap_architecture_template.yml
    parameters:
      arch: amd64
      qemu_arch: x86_64
      selectedArch: ${{ variables.architecture }}
  - template: debootstrap_architecture_template.yml
    parameters:
      arch: arm64
      qemu_arch: aarch64
      selectedArch: ${{ variables.architecture }}
