version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Installing build dependencies
          command: |
            sudo apt-get update -y -q
            sudo apt-get install -y -q curl gnupg debootstrap qemu-user-static
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
